const fs = require('fs');
const path = require('path');
const hw = path.join(__dirname, 'bimaru-harbor.html');
const html = fs.readFileSync(hw,'utf8');
let js = html.match(/<script>([\s\S]*)<\/script>/)[1];
js = js.replace("document.addEventListener('mouseup',()=>{drag=false; wasDrag=false;});", '');
js = js.replace('newGame();', '');
const bootstrap = `const dummyEl=()=>({textContent:'',className:'',innerHTML:'',addEventListener(){},classList:{add(){},remove(){}},dataset:{}}); global.document={getElementById(){return dummyEl();},querySelector(){return dummyEl();},querySelectorAll(){return [];},addEventListener(){}}; global.window=globalThis;`;
eval(bootstrap + js);
const SAMPLES = require(path.join(__dirname, 'harbor_samples.json'));
const sample = SAMPLES[Number(process.argv[2])-1];
if(!sample){ console.error('sample not found'); process.exit(1); }
const indices = (process.argv[3]||'').split(',').filter(Boolean).map(Number);
const water = (process.argv[4]||'').split(',').filter(Boolean).map(Number);
const clueMap={};
for(const [r,c,v] of sample.islands) clueMap[idx(r,c)]='i'+v;
for(const i of indices) clueMap[i]=clueTypeForCell(sample.flat, Math.floor(i/N), i%N);
for(const i of water) clueMap[i]='w';
const puz={grid:sample.flat.slice(), rc:sample.rows.slice(), cc:sample.cols.slice(), cl:clueMap, meta:{}};
const uniqueBudget = Number(process.argv[5] || 180000);
const noIslandBudget = Number(process.argv[6] || 200000);
const unique = countSolutionsForPuzzle(puz,2,uniqueBudget);
const noIs = countSolutionsForPuzzle(stripIslandClues(puz),2,noIslandBudget);
console.log(JSON.stringify({sample:Number(process.argv[2]), clues:Object.keys(clueMap).length, shipIndices:indices, waterIndices:water, uniqueBudget, noIslandBudget, unique, noIsland:noIs, clueMap}, null, 2));
